"""Add notification and post models

Revision ID: f418dcaa85cd
Revises: 06972fac7c85
Create Date: 2023-10-17 16:05:06.838203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f418dcaa85cd'
down_revision = '06972fac7c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thumbnail')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('bank_id', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('account_name', sa.String(length=150), nullable=True),
    sa.Column('network', sa.String(length=150), nullable=True),
    sa.Column('wallet_address', sa.String(length=150), nullable=True),
    sa.Column('coin', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    op.drop_table('notifications')
    op.drop_table('posts')
    # ### end Alembic commands ###
